name: ESLint

on:
  push:
    branches: ["main"]
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
  pull_request:
    branches: ["main"]
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-22.04
    container:
      image: node:20-slim
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false
